<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import EmailTemplateEditor from '$lib/components/EmailTemplateEditor.svelte';
  
  interface EmailTemplate {
    id: string;
    name: string;
    subject: string;
    htmlContent: string;
    textContent: string;
    variables: Array<{
      name: string;
      description: string;
      example: string;
    }>;
  }
  
  let templates: EmailTemplate[] = [];
  let selectedTemplate: EmailTemplate | null = null;
  let loading = false;
  let saving = false;
  let testLoading = false;
  let message = '';
  let messageType: 'success' | 'error' = 'success';
  
  // Default template
  const defaultTemplate: EmailTemplate = {
    id: 'default',
    name: 'Default Alert Notification',
    subject: '🚨 {{monitor_name}} Alert: {{trigger_reason}}',
    htmlContent: `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>Monitor Alert</title>
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
          <div style="background: linear-gradient(135deg, #0d47a1 0%, #1565c0 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center;">
            <h1 style="margin: 0; font-size: 24px;">📊 Monitor Alert</h1>
            <p style="margin: 10px 0 0; opacity: 0.9;">{{monitor_name}}</p>
          </div>
          
          <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-top: none; padding: 24px; border-radius: 0 0 8px 8px;">
            <div style="background: white; padding: 20px; border-radius: 6px; margin-bottom: 20px;">
              <h2 style="color: #0d47a1; margin: 0 0 16px; font-size: 18px;">Alert Details</h2>
              
              <table style="width: 100%; border-collapse: collapse;">
                <tr>
                  <td style="padding: 8px 0; font-weight: 600; color: #374151; width: 140px;">Status:</td>
                  <td style="padding: 8px 0; color: #1f2937;">{{monitor_status}}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: 600; color: #374151;">Current Value:</td>
                  <td style="padding: 8px 0; color: #1f2937; font-family: monospace; background: #f3f4f6; padding: 4px 8px; border-radius: 4px; font-size: 14px;">{{current_value}}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: 600; color: #374151;">Trigger:</td>
                  <td style="padding: 8px 0; color: #1f2937;">{{trigger_condition}}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: 600; color: #374151;">Time:</td>
                  <td style="padding: 8px 0; color: #6b7280; font-size: 14px;">{{timestamp}}</td>
                </tr>
              </table>
            </div>
            
            <div style="text-align: center; margin: 24px 0;">
              <a href="{{monitor_url}}" style="display: inline-block; background: #0d47a1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 14px;">View Monitor Details</a>
            </div>
            
            <div style="border-top: 1px solid #e5e7eb; padding-top: 16px; margin-top: 20px;">
              <p style="margin: 0; font-size: 12px; color: #9ca3af; text-align: center;">
                This alert was generated by <a href="{{dashboard_url}}" style="color: #0d47a1;">Monitors</a> • 
                <a href="{{unsubscribe_url}}" style="color: #6b7280;">Manage notifications</a>
              </p>
            </div>
          </div>
        </body>
      </html>
    `,
    textContent: `🚨 MONITOR ALERT: {{monitor_name}}

Alert Details:
Status: {{monitor_status}}
Current Value: {{current_value}}
Trigger Condition: {{trigger_condition}}
Time: {{timestamp}}

View Monitor: {{monitor_url}}

---
This alert was generated by Monitors
Dashboard: {{dashboard_url}}
Manage notifications: {{unsubscribe_url}}`,
    variables: [
      { name: 'monitor_name', description: 'Name of the monitor', example: 'Tesla Stock Price Tracker' },
      { name: 'monitor_status', description: 'Current alert status', example: 'Alert Triggered' },
      { name: 'current_value', description: 'Current monitored value', example: '$195.50' },
      { name: 'trigger_condition', description: 'What triggered the alert', example: 'Price dropped below $200.00' },
      { name: 'timestamp', description: 'When alert was triggered', example: 'January 15, 2024 at 10:30 AM EST' },
      { name: 'monitor_url', description: 'Link to monitor details', example: 'https://monitors.app/monitor/abc123' },
      { name: 'dashboard_url', description: 'Link to dashboard', example: 'https://monitors.app/dashboard' },
      { name: 'unsubscribe_url', description: 'Link to notification settings', example: 'https://monitors.app/settings/notifications' }
    ]
  };
  
  onMount(async () => {
    await loadTemplates();
  });
  
  async function loadTemplates() {
    loading = true;
    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 800));
      
      // Mock templates data
      templates = [
        { ...defaultTemplate },
        {
          id: 'urgent',
          name: 'Urgent Alert Template',
          subject: '🚨 URGENT: {{monitor_name}} - Immediate Action Required',
          htmlContent: defaultTemplate.htmlContent.replace('Monitor Alert', 'URGENT ALERT'),
          textContent: defaultTemplate.textContent.replace('MONITOR ALERT', 'URGENT ALERT'),
          variables: defaultTemplate.variables
        },
        {
          id: 'summary',
          name: 'Daily Summary Template',
          subject: '📊 Daily Summary: {{monitor_count}} monitors checked',
          htmlContent: `<html><body><h2>Daily Summary</h2><p>{{summary_content}}</p></body></html>`,
          textContent: `Daily Summary\n\n{{summary_content}}`,
          variables: [
            { name: 'monitor_count', description: 'Number of monitors', example: '5' },
            { name: 'summary_content', description: 'Summary content', example: 'All monitors operating normally' }
          ]
        }
      ];
      
      // Select first template by default
      selectedTemplate = templates[0];
    } catch (error) {
      showMessage('Failed to load templates', 'error');
    } finally {
      loading = false;
    }
  }
  
  function selectTemplate(template: EmailTemplate) {
    selectedTemplate = { ...template };
  }
  
  function createNewTemplate() {
    selectedTemplate = {
      id: '',
      name: 'New Template',
      subject: '{{monitor_name}} Alert',
      htmlContent: '<html><body><h2>{{monitor_name}} Alert</h2><p>{{trigger_condition}}</p></body></html>',
      textContent: '{{monitor_name}} Alert\n\n{{trigger_condition}}',
      variables: defaultTemplate.variables
    };
  }
  
  async function handleSave(event: CustomEvent<{ template: EmailTemplate }>) {
    const { template } = event.detail;
    saving = true;
    
    try {
      // Simulate API save
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      if (template.id) {
        // Update existing
        const index = templates.findIndex(t => t.id === template.id);
        if (index >= 0) {
          templates[index] = template;
        }
      } else {
        // Create new
        template.id = `template_${Date.now()}`;
        templates = [...templates, template];
      }
      
      templates = templates; // Trigger reactivity
      selectedTemplate = template;
      showMessage('Template saved successfully', 'success');
    } catch (error) {
      showMessage('Failed to save template', 'error');
    } finally {
      saving = false;
    }
  }
  
  async function handleTest(event: CustomEvent<{ template: EmailTemplate; testEmail: string }>) {
    const { template, testEmail } = event.detail;
    testLoading = true;
    
    try {
      // Simulate sending test email
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      showMessage(`Test email sent to ${testEmail}`, 'success');
    } catch (error) {
      showMessage('Failed to send test email', 'error');
    } finally {
      testLoading = false;
    }
  }
  
  function handleReset() {
    if (selectedTemplate) {
      selectedTemplate = { ...defaultTemplate };
      showMessage('Template reset to default', 'success');
    }
  }
  
  async function deleteTemplate(templateId: string) {
    if (templateId === 'default') {
      showMessage('Cannot delete default template', 'error');
      return;
    }
    
    if (!confirm('Are you sure you want to delete this template?')) {
      return;
    }
    
    try {
      templates = templates.filter(t => t.id !== templateId);
      
      if (selectedTemplate?.id === templateId) {
        selectedTemplate = templates[0] || null;
      }
      
      showMessage('Template deleted', 'success');
    } catch (error) {
      showMessage('Failed to delete template', 'error');
    }
  }
  
  function showMessage(text: string, type: 'success' | 'error') {
    message = text;
    messageType = type;
    setTimeout(() => {
      message = '';
    }, 4000);
  }
</script>

<svelte:head>
  <title>Email Templates - Monitors</title>
</svelte:head>

<div class="email-templates-page">
  <!-- Page header -->
  <div class="page-header">
    <div class="header-content">
      <div class="header-text">
        <h1 class="page-title">Email Template Configuration</h1>
        <p class="page-description">
          Customize notification email templates with dynamic variables and preview functionality
        </p>
      </div>
      
      <div class="header-actions">
        <button 
          class="btn-primary"
          on:click={createNewTemplate}
        >
          ➕ New Template
        </button>
      </div>
    </div>
    
    <!-- Message display -->
    {#if message}
      <div class="message" class:success={messageType === 'success'} class:error={messageType === 'error'}>
        {#if messageType === 'success'}✅{:else}❌{/if}
        {message}
      </div>
    {/if}
  </div>
  
  <div class="templates-container">
    <!-- Templates sidebar -->
    <div class="templates-sidebar">
      <div class="sidebar-header">
        <h2 class="sidebar-title">Email Templates</h2>
        {#if loading}
          <div class="loading-spinner"></div>
        {/if}
      </div>
      
      <div class="templates-list">
        {#each templates as template}
          <div 
            class="template-item"
            class:active={selectedTemplate?.id === template.id}
          >
            <button
              class="template-button"
              on:click={() => selectTemplate(template)}
            >
              <div class="template-info">
                <div class="template-name">{template.name}</div>
                <div class="template-subject">{template.subject}</div>
              </div>
            </button>
            
            {#if template.id !== 'default'}
              <button
                class="delete-button"
                on:click={() => deleteTemplate(template.id)}
                aria-label="Delete template"
                title="Delete template"
              >
                🗑️
              </button>
            {/if}
          </div>
        {/each}
        
        {#if templates.length === 0 && !loading}
          <div class="empty-state">
            <div class="empty-icon">📧</div>
            <p>No templates found</p>
          </div>
        {/if}
      </div>
    </div>
    
    <!-- Template editor -->
    <div class="template-editor">
      {#if selectedTemplate}
        <EmailTemplateEditor
          bind:template={selectedTemplate}
          loading={saving || testLoading}
          on:save={handleSave}
          on:test={handleTest}
          on:reset={handleReset}
        />
      {:else}
        <div class="no-template-selected">
          <div class="no-template-icon">📝</div>
          <h3>Select a Template</h3>
          <p>Choose a template from the sidebar to edit, or create a new one.</p>
          <button class="btn-primary" on:click={createNewTemplate}>
            ➕ Create New Template
          </button>
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  .email-templates-page {
    max-width: 1400px;
    margin: 0 auto;
    padding: 2rem;
  }
  
  /* Page header */
  .page-header {
    margin-bottom: 2rem;
  }
  
  .header-content {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 2rem;
    margin-bottom: 1rem;
  }
  
  .header-text {
    flex: 1;
  }
  
  .page-title {
    font-size: 2rem;
    font-weight: 700;
    color: #1f2937;
    margin: 0 0 0.5rem 0;
  }
  
  .page-description {
    color: #6b7280;
    font-size: 1.125rem;
    margin: 0;
    max-width: 600px;
  }
  
  .header-actions {
    display: flex;
    align-items: center;
    gap: 1rem;
  }
  
  /* Message */
  .message {
    padding: 1rem;
    border-radius: 8px;
    font-weight: 500;
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }
  
  .message.success {
    background: #d1fae5;
    color: #065f46;
    border: 1px solid #a7f3d0;
  }
  
  .message.error {
    background: #fee2e2;
    color: #991b1b;
    border: 1px solid #fecaca;
  }
  
  /* Templates container */
  .templates-container {
    display: grid;
    grid-template-columns: 300px 1fr;
    gap: 2rem;
    height: calc(100vh - 200px);
  }
  
  /* Templates sidebar */
  .templates-sidebar {
    display: flex;
    flex-direction: column;
    background: white;
    border: 1px solid #e5e7eb;
    border-radius: 12px;
    overflow: hidden;
  }
  
  .sidebar-header {
    padding: 1.5rem;
    border-bottom: 1px solid #e5e7eb;
    background: #f9fafb;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  
  .sidebar-title {
    font-size: 1.125rem;
    font-weight: 600;
    color: #1f2937;
    margin: 0;
  }
  
  .templates-list {
    flex: 1;
    overflow-y: auto;
    padding: 1rem 0;
  }
  
  .template-item {
    display: flex;
    align-items: center;
    margin: 0 1rem 0.5rem 1rem;
    border-radius: 8px;
    overflow: hidden;
    border: 1px solid transparent;
    transition: all 0.2s ease;
  }
  
  .template-item.active {
    border-color: var(--primary);
    background: rgba(13, 71, 161, 0.05);
  }
  
  .template-button {
    flex: 1;
    display: block;
    padding: 1rem;
    border: none;
    background: none;
    cursor: pointer;
    text-align: left;
    transition: all 0.2s ease;
  }
  
  .template-button:hover {
    background: rgba(13, 71, 161, 0.05);
  }
  
  .template-info {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }
  
  .template-name {
    font-weight: 600;
    color: #1f2937;
    font-size: 0.875rem;
  }
  
  .template-subject {
    font-size: 0.75rem;
    color: #6b7280;
    line-height: 1.3;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }
  
  .delete-button {
    width: 36px;
    height: 36px;
    border: none;
    background: none;
    color: #9ca3af;
    cursor: pointer;
    border-radius: 4px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.875rem;
    transition: all 0.2s ease;
    margin-right: 0.5rem;
  }
  
  .delete-button:hover,
  .delete-button:focus {
    background: #fef2f2;
    color: #dc2626;
  }
  
  .empty-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 2rem 1rem;
    color: #6b7280;
    text-align: center;
  }
  
  .empty-icon {
    font-size: 3rem;
    margin-bottom: 1rem;
    opacity: 0.5;
  }
  
  /* Template editor */
  .template-editor {
    overflow-y: auto;
    border: 1px solid #e5e7eb;
    border-radius: 12px;
    background: white;
  }
  
  .no-template-selected {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    text-align: center;
    padding: 2rem;
    color: #6b7280;
  }
  
  .no-template-icon {
    font-size: 4rem;
    margin-bottom: 1rem;
    opacity: 0.5;
  }
  
  .no-template-selected h3 {
    font-size: 1.25rem;
    font-weight: 600;
    color: #1f2937;
    margin: 0 0 0.5rem 0;
  }
  
  .no-template-selected p {
    margin: 0 0 1.5rem 0;
    max-width: 400px;
  }
  
  /* Buttons */
  .btn-primary {
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.75rem 1.5rem;
    background: var(--primary);
    color: white;
    border: 2px solid var(--primary);
    border-radius: 8px;
    font-weight: 500;
    font-size: 0.875rem;
    cursor: pointer;
    transition: all 0.2s ease;
    text-decoration: none;
    justify-content: center;
    min-height: 44px;
  }
  
  .btn-primary:hover:not(:disabled) {
    background: #1565c0;
    border-color: #1565c0;
  }
  
  .btn-primary:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
  .loading-spinner {
    width: 16px;
    height: 16px;
    border: 2px solid #d1d5db;
    border-radius: 50%;
    border-top-color: var(--primary);
    animation: spin 1s linear infinite;
  }
  
  @keyframes spin {
    to { transform: rotate(360deg); }
  }
  
  /* Mobile responsive */
  @media (max-width: 1024px) {
    .templates-container {
      grid-template-columns: 250px 1fr;
    }
  }
  
  @media (max-width: 768px) {
    .email-templates-page {
      padding: 1rem;
    }
    
    .page-title {
      font-size: 1.5rem;
    }
    
    .page-description {
      font-size: 1rem;
    }
    
    .header-content {
      flex-direction: column;
      align-items: stretch;
      gap: 1rem;
    }
    
    .templates-container {
      grid-template-columns: 1fr;
      height: auto;
    }
    
    .templates-sidebar {
      order: 2;
      max-height: 300px;
    }
    
    .template-editor {
      order: 1;
    }
  }
  
  /* Accessibility */
  @media (prefers-reduced-motion: reduce) {
    .template-item,
    .template-button,
    .delete-button,
    .btn-primary {
      transition: none;
    }
    
    .loading-spinner {
      animation: none;
    }
  }
  
  /* Scrollbar styling */
  .templates-list::-webkit-scrollbar,
  .template-editor::-webkit-scrollbar {
    width: 6px;
  }
  
  .templates-list::-webkit-scrollbar-track,
  .template-editor::-webkit-scrollbar-track {
    background: transparent;
  }
  
  .templates-list::-webkit-scrollbar-thumb,
  .template-editor::-webkit-scrollbar-thumb {
    background: #d1d5db;
    border-radius: 3px;
  }
  
  .templates-list::-webkit-scrollbar-thumb:hover,
  .template-editor::-webkit-scrollbar-thumb:hover {
    background: #9ca3af;
  }
</style>