import { p as push, c as push_element, d as pop_element, i as attr, m as maybe_selected, f as attr_class, a as pop, F as FILENAME, g as stringify } from "../../../chunks/index3.js";
_page[FILENAME] = "src/routes/settings/+page.svelte";
function _page($$payload, $$props) {
  push(_page);
  let loading = false;
  let settings = {
    email: "",
    name: "",
    notifications: { email: true, push: false, frequency: "immediate" },
    preferences: { timezone: "UTC", theme: "light" }
  };
  $$payload.out.push(`<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">`);
  push_element($$payload, "div", 81, 0);
  $$payload.out.push(`<div class="mb-8">`);
  push_element($$payload, "div", 83, 2);
  $$payload.out.push(`<nav class="flex" aria-label="Breadcrumb">`);
  push_element($$payload, "nav", 84, 4);
  $$payload.out.push(`<ol role="list" class="flex items-center space-x-4">`);
  push_element($$payload, "ol", 85, 6);
  $$payload.out.push(`<li>`);
  push_element($$payload, "li", 86, 8);
  $$payload.out.push(`<a href="/" class="text-gray-400 hover:text-gray-500">`);
  push_element($$payload, "a", 87, 10);
  $$payload.out.push(`<span class="sr-only">`);
  push_element($$payload, "span", 88, 12);
  $$payload.out.push(`Home</span>`);
  pop_element();
  $$payload.out.push(` Dashboard</a>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(` <li>`);
  push_element($$payload, "li", 92, 8);
  $$payload.out.push(`<div class="flex items-center">`);
  push_element($$payload, "div", 93, 10);
  $$payload.out.push(`<span class="text-gray-400 mx-4">`);
  push_element($$payload, "span", 94, 12);
  $$payload.out.push(`/</span>`);
  pop_element();
  $$payload.out.push(` <span class="text-gray-900 font-medium">`);
  push_element($$payload, "span", 95, 12);
  $$payload.out.push(`Settings</span>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(`</ol>`);
  pop_element();
  $$payload.out.push(`</nav>`);
  pop_element();
  $$payload.out.push(` <h1 class="mt-4 text-3xl font-bold text-gray-900">`);
  push_element($$payload, "h1", 101, 4);
  $$payload.out.push(`Account Settings</h1>`);
  pop_element();
  $$payload.out.push(` <p class="mt-2 text-gray-600">`);
  push_element($$payload, "p", 102, 4);
  $$payload.out.push(`Manage your account preferences and notifications</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="bg-white shadow-lg rounded-lg overflow-hidden">`);
  push_element($$payload, "div", 106, 2);
  $$payload.out.push(`<form class="divide-y divide-gray-200">`);
  push_element($$payload, "form", 107, 4);
  {
    $$payload.out.push("<!--[!-->");
  }
  $$payload.out.push(`<!--]--> `);
  {
    $$payload.out.push("<!--[!-->");
  }
  $$payload.out.push(`<!--]--> <div class="p-6">`);
  push_element($$payload, "div", 126, 6);
  $$payload.out.push(`<h3 class="text-lg font-medium text-gray-900 mb-4">`);
  push_element($$payload, "h3", 127, 8);
  $$payload.out.push(`Profile Information</h3>`);
  pop_element();
  $$payload.out.push(` <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">`);
  push_element($$payload, "div", 128, 8);
  $$payload.out.push(`<div>`);
  push_element($$payload, "div", 129, 10);
  $$payload.out.push(`<label for="name" class="block text-sm font-medium text-gray-700 mb-2">`);
  push_element($$payload, "label", 130, 12);
  $$payload.out.push(`Full Name</label>`);
  pop_element();
  $$payload.out.push(` <input id="name" type="text"${attr("value", settings.name)} placeholder="Enter your full name" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"/>`);
  push_element($$payload, "input", 133, 12);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div>`);
  push_element($$payload, "div", 141, 10);
  $$payload.out.push(`<label for="email" class="block text-sm font-medium text-gray-700 mb-2">`);
  push_element($$payload, "label", 142, 12);
  $$payload.out.push(`Email Address</label>`);
  pop_element();
  $$payload.out.push(` <input id="email" type="email"${attr("value", settings.email)} placeholder="your@email.com" disabled class="block w-full rounded-md border-gray-300 shadow-sm bg-gray-50 text-gray-500"/>`);
  push_element($$payload, "input", 145, 12);
  pop_element();
  $$payload.out.push(` <p class="text-xs text-gray-500 mt-1">`);
  push_element($$payload, "p", 153, 12);
  $$payload.out.push(`Email cannot be changed</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="p-6">`);
  push_element($$payload, "div", 159, 6);
  $$payload.out.push(`<h3 class="text-lg font-medium text-gray-900 mb-4">`);
  push_element($$payload, "h3", 160, 8);
  $$payload.out.push(`Notification Preferences</h3>`);
  pop_element();
  $$payload.out.push(` <div class="space-y-4">`);
  push_element($$payload, "div", 161, 8);
  $$payload.out.push(`<div class="flex items-center justify-between">`);
  push_element($$payload, "div", 162, 10);
  $$payload.out.push(`<div>`);
  push_element($$payload, "div", 163, 12);
  $$payload.out.push(`<label for="email-notifications" class="text-sm font-medium text-gray-700">`);
  push_element($$payload, "label", 164, 14);
  $$payload.out.push(`Email Notifications</label>`);
  pop_element();
  $$payload.out.push(` <p class="text-sm text-gray-500">`);
  push_element($$payload, "p", 167, 14);
  $$payload.out.push(`Receive monitor alerts via email</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <input id="email-notifications" type="checkbox"${attr("checked", settings.notifications.email, true)} class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"/>`);
  push_element($$payload, "input", 169, 12);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="flex items-center justify-between">`);
  push_element($$payload, "div", 177, 10);
  $$payload.out.push(`<div>`);
  push_element($$payload, "div", 178, 12);
  $$payload.out.push(`<label for="push-notifications" class="text-sm font-medium text-gray-700">`);
  push_element($$payload, "label", 179, 14);
  $$payload.out.push(`Push Notifications</label>`);
  pop_element();
  $$payload.out.push(` <p class="text-sm text-gray-500">`);
  push_element($$payload, "p", 182, 14);
  $$payload.out.push(`Receive browser push notifications</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <input id="push-notifications" type="checkbox"${attr("checked", settings.notifications.push, true)} class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"/>`);
  push_element($$payload, "input", 184, 12);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div>`);
  push_element($$payload, "div", 192, 10);
  $$payload.out.push(`<label for="frequency" class="block text-sm font-medium text-gray-700 mb-2">`);
  push_element($$payload, "label", 193, 12);
  $$payload.out.push(`Notification Frequency</label>`);
  pop_element();
  $$payload.out.push(` <select id="frequency" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500">`);
  push_element($$payload, "select", 196, 12);
  $$payload.select_value = settings.notifications.frequency;
  $$payload.out.push(`<option value="immediate"${maybe_selected($$payload, "immediate")}>`);
  push_element($$payload, "option", 201, 14);
  $$payload.out.push(`Immediate</option>`);
  pop_element();
  $$payload.out.push(`<option value="hourly"${maybe_selected($$payload, "hourly")}>`);
  push_element($$payload, "option", 202, 14);
  $$payload.out.push(`Hourly Digest</option>`);
  pop_element();
  $$payload.out.push(`<option value="daily"${maybe_selected($$payload, "daily")}>`);
  push_element($$payload, "option", 203, 14);
  $$payload.out.push(`Daily Digest</option>`);
  pop_element();
  $$payload.out.push(`<option value="weekly"${maybe_selected($$payload, "weekly")}>`);
  push_element($$payload, "option", 204, 14);
  $$payload.out.push(`Weekly Summary</option>`);
  pop_element();
  $$payload.select_value = void 0;
  $$payload.out.push(`</select>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="p-6">`);
  push_element($$payload, "div", 211, 6);
  $$payload.out.push(`<h3 class="text-lg font-medium text-gray-900 mb-4">`);
  push_element($$payload, "h3", 212, 8);
  $$payload.out.push(`Preferences</h3>`);
  pop_element();
  $$payload.out.push(` <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">`);
  push_element($$payload, "div", 213, 8);
  $$payload.out.push(`<div>`);
  push_element($$payload, "div", 214, 10);
  $$payload.out.push(`<label for="timezone" class="block text-sm font-medium text-gray-700 mb-2">`);
  push_element($$payload, "label", 215, 12);
  $$payload.out.push(`Timezone</label>`);
  pop_element();
  $$payload.out.push(` <select id="timezone" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500">`);
  push_element($$payload, "select", 218, 12);
  $$payload.select_value = settings.preferences.timezone;
  $$payload.out.push(`<option value="UTC"${maybe_selected($$payload, "UTC")}>`);
  push_element($$payload, "option", 223, 14);
  $$payload.out.push(`UTC</option>`);
  pop_element();
  $$payload.out.push(`<option value="America/New_York"${maybe_selected($$payload, "America/New_York")}>`);
  push_element($$payload, "option", 224, 14);
  $$payload.out.push(`Eastern Time</option>`);
  pop_element();
  $$payload.out.push(`<option value="America/Chicago"${maybe_selected($$payload, "America/Chicago")}>`);
  push_element($$payload, "option", 225, 14);
  $$payload.out.push(`Central Time</option>`);
  pop_element();
  $$payload.out.push(`<option value="America/Denver"${maybe_selected($$payload, "America/Denver")}>`);
  push_element($$payload, "option", 226, 14);
  $$payload.out.push(`Mountain Time</option>`);
  pop_element();
  $$payload.out.push(`<option value="America/Los_Angeles"${maybe_selected($$payload, "America/Los_Angeles")}>`);
  push_element($$payload, "option", 227, 14);
  $$payload.out.push(`Pacific Time</option>`);
  pop_element();
  $$payload.out.push(`<option value="Europe/London"${maybe_selected($$payload, "Europe/London")}>`);
  push_element($$payload, "option", 228, 14);
  $$payload.out.push(`London</option>`);
  pop_element();
  $$payload.out.push(`<option value="Europe/Paris"${maybe_selected($$payload, "Europe/Paris")}>`);
  push_element($$payload, "option", 229, 14);
  $$payload.out.push(`Paris</option>`);
  pop_element();
  $$payload.out.push(`<option value="Asia/Tokyo"${maybe_selected($$payload, "Asia/Tokyo")}>`);
  push_element($$payload, "option", 230, 14);
  $$payload.out.push(`Tokyo</option>`);
  pop_element();
  $$payload.select_value = void 0;
  $$payload.out.push(`</select>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div>`);
  push_element($$payload, "div", 234, 10);
  $$payload.out.push(`<label for="theme" class="block text-sm font-medium text-gray-700 mb-2">`);
  push_element($$payload, "label", 235, 12);
  $$payload.out.push(`Theme</label>`);
  pop_element();
  $$payload.out.push(` <select id="theme" class="block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500">`);
  push_element($$payload, "select", 238, 12);
  $$payload.select_value = settings.preferences.theme;
  $$payload.out.push(`<option value="light"${maybe_selected($$payload, "light")}>`);
  push_element($$payload, "option", 243, 14);
  $$payload.out.push(`Light</option>`);
  pop_element();
  $$payload.out.push(`<option value="dark"${maybe_selected($$payload, "dark")}>`);
  push_element($$payload, "option", 244, 14);
  $$payload.out.push(`Dark</option>`);
  pop_element();
  $$payload.out.push(`<option value="auto"${maybe_selected($$payload, "auto")}>`);
  push_element($$payload, "option", 245, 14);
  $$payload.out.push(`Auto</option>`);
  pop_element();
  $$payload.select_value = void 0;
  $$payload.out.push(`</select>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="px-6 py-4 bg-gray-50 flex justify-end space-x-3">`);
  push_element($$payload, "div", 252, 6);
  $$payload.out.push(`<a href="/" class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">`);
  push_element($$payload, "a", 253, 8);
  $$payload.out.push(`Cancel</a>`);
  pop_element();
  $$payload.out.push(` <button type="submit"${attr("disabled", loading, true)}${attr_class(`px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 ${stringify("")}`)}>`);
  push_element($$payload, "button", 259, 8);
  {
    $$payload.out.push("<!--[!-->");
    $$payload.out.push(`Save Changes`);
  }
  $$payload.out.push(`<!--]--></button>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</form>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="mt-8 bg-white shadow-lg rounded-lg overflow-hidden border border-red-200">`);
  push_element($$payload, "div", 279, 2);
  $$payload.out.push(`<div class="p-6">`);
  push_element($$payload, "div", 280, 4);
  $$payload.out.push(`<h3 class="text-lg font-medium text-red-900 mb-2">`);
  push_element($$payload, "h3", 281, 6);
  $$payload.out.push(`Danger Zone</h3>`);
  pop_element();
  $$payload.out.push(` <p class="text-sm text-red-600 mb-4">`);
  push_element($$payload, "p", 282, 6);
  $$payload.out.push(`These actions cannot be undone</p>`);
  pop_element();
  $$payload.out.push(` <div class="space-y-3">`);
  push_element($$payload, "div", 284, 6);
  $$payload.out.push(`<button type="button" class="px-4 py-2 text-sm font-medium text-red-700 bg-red-50 border border-red-200 rounded-md hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">`);
  push_element($$payload, "button", 285, 8);
  $$payload.out.push(`Delete All Monitors</button>`);
  pop_element();
  $$payload.out.push(` <button type="button" class="px-4 py-2 text-sm font-medium text-red-700 bg-red-50 border border-red-200 rounded-md hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">`);
  push_element($$payload, "button", 292, 8);
  $$payload.out.push(`Delete Account</button>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  pop();
}
_page.render = function() {
  throw new Error("Component.render(...) is no longer valid in Svelte 5. See https://svelte.dev/docs/svelte/v5-migration-guide#Components-are-no-longer-classes for more information");
};
export {
  _page as default
};
